name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.9'
        architecture: 'x64'
    - name: Install
      run: |
        python3 -m pip install -e .
        pip3 install nose mock
    - name: Tests
      run: 
        nosetests -v --nocapture -s
